# -*- coding: utf-8 -*-
# Generated by Django 1.9.11 on 2016-11-08 00:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Mascota', '0002_auto_20161108_0038'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mascota',
            name='folio',
        ),
        migrations.AddField(
            model_name='mascota',
            name='id',
            field=models.AutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
